VOC_type: bbox
batch_size: 32
dataset_name: VOC
dataset_path: /mnt/dataset/
device: cuda
input_size: 224
mask_type: segm
model_name: efficientnet_b0
model_path: /mnt/checkpoints/VOC/efficientnet_b0/VOC_efficientnet_b0
num_batches_to_process: 300
num_batches_to_process_pixel_flipping: 50
save_dir: /mnt/outputs/
seed: 1
xai_method: null
