annotation_path: <IMAGENET_ANNOTATION_PATH>
batch_size: 32
dataset_name: imagenet
dataset_path: <IMAGENET_IMAGE_PATH>
device: cuda
input_size: 224
label_map_path: other_files/label-map-imagenet.json
model_name: vgg16
num_batches_to_process: 20
num_batches_to_process_pixel_flipping: 10
save_dir: test_outputs/
seed: 1
word_net_ids:
- n03982430
xai_method: excitation_backprop_vgg_canonized
