annotation_path: /mnt/MS_data/annotations/instances_val2014.json
batch_size: 32
classes:
- 21
dataset_name: MS
dataset_path: /mnt/MS_data/val2014
device: cuda
input_size: 224
mask_type: segm
model_name: resnet18
model_path: /mnt/checkpoints/MS/resnet18/MS_resnet18
num_batches_to_process: 300
num_batches_to_process_pixel_flipping: 50
save_dir: /mnt/outputs/
seed: 1
xai_method: excitation_backprop_resnet_canonized
