annotation_path: /mnt/MS_data/annotations/instances_val2014.json
batch_size: 32
classes:
- 51
dataset_name: MS
dataset_path: /mnt/MS_data/val2014
device: cuda
input_size: 224
mask_type: segm
model_name: resnet50
model_path: /mnt/checkpoints/MS/resnet50/MS_resnet50
num_batches_to_process: 300
num_batches_to_process_pixel_flipping: 50
save_dir: /mnt/outputs/
seed: 1
xai_method: lrp_a2b1_resnet
